- id: mix-format
  name: mix format
  description: Formats Elixir files with mix format.
  language: system
  entry: mix format
  files: \.exs?$
- id: mix-credo
  name: mix credo
  description: Analyses Elixir files with mix credo
  language: system
  entry: mix credo --strict
  files: \.exs?$
